### ISSUE TITLE
Token failure, add troubleshoot tips to Q&A

### ISSUE THREAD

**Issue by rickballard** [Melvin-Abraham/gaudc-wiki#2] opened 2022-12-03 20:57 UTC
When getting the token at the end of the setup process, it may help to delete the s from the https:\\ in the URL that delivers the token code.  However, despite success in getting the token code, failure to verify may still occur, (e.g. Cannot GET /auth/success/%20failed%20to%20get%20token), in which case it may help to wait a few days and try that part of the setup process again.  Also, restarting the PC around this time might help...?

**Comment by Melvin-Abraham** [comment] 2023-01-01 08:39
_Duplicate of #1_

**Comment by Melvin-Abraham** [comment] 2023-01-01 11:40
This issue has been addressed and an FAQ section for the same has been added. Refer [FAQ: Why am I getting SSL Protocol Error when assistant opens localhost?](https://github.com/Melvin-Abraham/Google-Assistant-Unofficial-Desktop-Client/wiki/Frequently-Asked-Questions-(FAQ)#why-am-i-getting-ssl-protocol-error-when-assistant-opens-localhost)

**Comment by Melvin-Abraham** [comment] 2023-01-01 11:40
_Closing as resolved_

**Closed as completed by Melvin-Abraham** 2023-01-01 11:40 UTC
